name: Update Pages

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          git config --global user.email "automated.deploy.end-of-covid@rerere.org"
          git config --global user.name "Automated Deploy"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy
        run: |-
          ./deploy.sh
